const mongoose = require("mongoose");
const AssignmentState = require("./assignmentstate.model"); 
const Area = require("./area.model"); 

// 1. DEFINE THE SCHEMA FIRST
const ReportSchema = new mongoose.Schema(
  {
    // MongoDB will generate a default ObjectId (_id)
    
    category: {
      type: String,
      required: true,
    },
    description: {
      type: String,
      required: true,
    },
    location: {
      type: {
        type: String,
        enum: ['Point'],
        required: true
      },
      coordinates: {
        type: [Number],
        required: true
      }
    },
    area: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Area",
    },
    mediaPath: {
      type: String,
      required: true,
    },
    mediaType: {
      type: String,
      enum: ['image', 'video'],
      required: true
    },
    // NEW FIELDS for Resolution Proof (Confirmed existing in files)
    resolutionMediaPath: {
      type: String,
      required: false,
    },
    resolutionMediaType: {
      type: String,
      enum: ['image', 'video'],
      required: false
    },
    submittedBy: {
      // CRITICAL FIX: Changed from ObjectId to String to accept the Firebase UID
      type: String, 
      // FIX: Revert to single string. Controller will handle manual population across user collections.
      ref: "Citizen",
    },
    assignedTo: {
        type: mongoose.Schema.Types.ObjectId,
        // FIX: Revert to single string. Controller will handle manual population across user collections.
        ref: "WorkerUser", 
        required: false,
    },
    status: {
      type: String,
      // MODIFIED: Added 'Review Required' and 'Rejected' statuses
      enum: ["Pending", "In Progress", "Resolved", "Review Required", "Rejected"], 
      default: "Pending",
    },
    priority: {
      type: String,
      enum: ["Low", "Medium", "High"],
      default: "Medium",
    },

    trashPriorityTag: { // 💡 MODIFIED: Renamed 'priority' to 'trashPriorityTag'
      type: String,
      // 💡 MODIFIED: Changed enum values to match the feature request
      enum: ["Small", "Medium", "High"],
      default: "Small", // Set default to 'Small' (low priority) until classified
    },
    
    // CRITICAL FIX: The ID is generated by the pre-save hook
    customReportId: {
      type: String,
      required: true, // Now required because the pre-save hook ensures it exists
      unique: true,
    },
    
    // NEW FIELD: Record the time the report was resolved.
    resolvedAt: {
        type: Date,
        default: null,
    },
    // NEW FIELD: Store the reason for rejection (mandatory if status is 'Rejected')
    rejectionReason: {
        type: String,
        required: false,
    },
  },
  { 
      timestamps: true,
      // Allow MongoDB to generate the standard ObjectId (_id)
  }
);


// 2. ATTACH THE PRE-SAVE HOOK AFTER DEFINITION
ReportSchema.pre('save', async function(next) {
    // Only generate the ID if it is a new document and the ID hasn't been set
    if (this.isNew && !this.customReportId) {
        
        const areaId = this.area;
        
        // --- 1. Get Area Name for Code ---
        const areaDoc = await Area.findById(areaId).select('name');
        if (!areaDoc) {
             return next(new Error("Area ID not found during custom ID generation."));
        }
        const areaName = areaDoc.name;

        // --- 2. Generate Date Component (MMDD) -> 4 digits ---
        const today = new Date();
        const mm = (today.getMonth() + 1).toString().padStart(2, '0'); // 01 to 12
        const dd = today.getDate().toString().padStart(2, '0'); // 01 to 31
        const dateComponent = `${mm}${dd}`; // MMDD (e.g., 1209)

        // --- 3. Generate Area Component (First 3 characters of cleaned name) -> 3 chars ---
        const cleanedName = areaName.toUpperCase().replace(/[^A-Z0-9]/g, '');
        const areaComponent = cleanedName.substring(0, 3).padEnd(3, 'X');
        
        // --- 4. Get Sequential Counter (001 to 999) -> 3 chars ---
        const todayStart = new Date();
        todayStart.setHours(0, 0, 0, 0); // Start of today

        // Find and atomically update/reset the counter
        let state = await AssignmentState.findOne({ area: areaId });
        let counter = 1;

        if (state) {
            if (new Date(state.lastAssignmentDate) < todayStart) {
                // New day, reset counter to 1
                state.reportCounter = 1;
            } else {
                // Same day, increment counter
                state.reportCounter += 1;
            }
            state.lastAssignmentDate = new Date();
            // Use updateOne to ensure atomicity for the counter logic
            await AssignmentState.updateOne({ area: areaId }, { reportCounter: state.reportCounter, lastAssignmentDate: state.lastAssignmentDate }, { upsert: true });
            
            counter = state.reportCounter;
        } else {
            // First ever report for this area, initialize state
            await AssignmentState.create({ area: areaId, reportCounter: 1, lastAssignmentDate: new Date() });
            counter = 1;
        }
        const counterComponent = counter.toString().padStart(3, '0');
        
        // --- 5. Assign the final 10-character ID ---
        this.customReportId = `${dateComponent}${areaComponent}${counterComponent}`; // e.g., 1209BEL001
    }
    
    // Ensure the ID is uppercase for consistent searching/indexing
    if (this.customReportId) {
        this.customReportId = this.customReportId.toUpperCase();
    }
    
    next();
});

ReportSchema.index({ location: '2dsphere' });

module.exports = mongoose.model("Report", ReportSchema);